### ISSUE TITLE
Fails to compile with binutils 2.42+ for 32-bit arm

### ISSUE THREAD

**Issue by OldManYellsAtCloud** [RPi-Distro/ffmpeg#11]
While trying to compile ffmpeg with the meta-raspberry Yocto layer for 32-bit arm target, I hit this bug: https://trac.ffmpeg.org/ticket/11074

It has been already fixed upstream:  http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=654bd47716c4f36719fb0f3f7fd8386d5ed0b916 

Would that be possible to get this fix into this repo somehow?

(If a generic garden-variety PR is acceptable with these changes, I can do that too)

**Comment by XECDesign** [comment]
Would that actually help? If the commit was added to this repo it would just show up as a patch file in `./debian/patches/`, it wouldn't actually be applied to the files from upstream.

**Comment by OldManYellsAtCloud** [comment]
I'm afraid not, this wouldn't help me unfortunately. If you say that cherry picking it isn't that easy to modify the actual file, I could also go one layer further, and try getting the change into meta-raspberrypi layer (having the change in this repo would be the cleanest, but it's not like I'm out of options)

**Comment by XECDesign** [comment]
Yeah, this repo is specifically for Debian packaging, which keeps upstream files as-is and the packaging separate in the `debian` directory. Patching the upstream files directly will lead to build issues for us.
