### ISSUE TITLE
no issues just question

### ISSUE THREAD

**Issue by spookyfirehorse** [RPi-Distro/ffmpeg#5]
hi !

thank you for your work

where is ffmpeg 4.3.3 with sand and the good stuff

is it possible to add to this repro 
or please some link

reguards spooky

**Comment by popcornmix** [comment]
You can install the source used using `apt get source`.
But the repo it comes from is: https://github.com/jc-kynesim/rpi-ffmpeg/

You should be able to find the matching release from the [tags](https://github.com/jc-kynesim/rpi-ffmpeg/tags)

**Comment by XECDesign** [comment]
Everything we ship in apt is already in this repo.

If you're not building using debuild and just want to apply the patches, take a look at https://wiki.debian.org/UsingQuilt
