### ISSUE TITLE
impossible to compile

### ISSUE THREAD

**Issue by spookyfirehorse** [RPi-Distro/ffmpeg#8]
git clone -b pios/bookworm https://github.com/RPi-Distro/ffmpeg.git

dpkg-buildpackage -us -uc
dpkg-buildpackage: Information: Quellpaket ffmpeg
dpkg-buildpackage: Information: Quellversion 8:5.1.4-0+rpt1+deb12u1
dpkg-buildpackage: Information: Quelldistribution bookworm-security
dpkg-buildpackage: Information: Quelle geändert durch Serge Schneider <serge@raspberrypi.com>
dpkg-buildpackage: Information: Host-Architektur arm64
 dpkg-source --before-build .
 debian/rules clean
dh clean --with pkgkde_symbolshelper
   debian/rules override_dh_auto_clean
make[1]: Verzeichnis „/home/spook/tmp/ffmpeg“ wird betreten
rm -rf debian/standard debian/extra debian/static
make[1]: Verzeichnis „/home/spook/tmp/ffmpeg“ wird verlassen
   dh_clean
 dpkg-source -b .
dpkg-source: Fehler: unmöglich, mit Quellformat »3.0 (quilt)« zu bauen: unter ../ffmpeg_5.1.4.orig.tar.{bz2,gz,lzma,xz} wurde kein Tarball der Originalautoren gefunden
dpkg-buildpackage: Fehler: Unterprozess dpkg-source -b . lieferte Exitstatus 255

normal configure witch works  on jc-kynesim github

./configure --prefix=/usr --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray    --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --disable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl  --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64  --enable-librsvg --enable-libdc1394 --enable-libdrm  --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared  --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-nonfree --enable-libfdk-aac --disable-static --disable-cuda --enable-vaapi --disable-vdpau  --enable-vulkan  --disable-nvdec --disable-nvenc --disable-cuvid --disable-cuda-llvm --disable-cuda-nvcc --disable-ffnvcodec  --enable-neon  --enable-v4l2-request  --enable-libudev   --enable-epoxy  && make -j4 && sudo make -j4 install
Unknown option "--enable-v4l2-request".

how is it possible to install ffmpeg with all supported codecs like vaapi-v4l2 and please the right --cpu=cortex inf for rpi 3 and 4 and 5

**Comment by XECDesign** [comment]
It looks like the quilt patches are not being applied. I think it should build if you fix this error:

> dpkg-source: Fehler: unmöglich, mit Quellformat »3.0 (quilt)« zu bauen: unter ../ffmpeg_5.1.4.orig.tar.{bz2,gz,lzma,xz} wurde kein Tarball der Originalautoren gefunden
> dpkg-buildpackage: Fehler: Unterprozess dpkg-source -b . lieferte Exitstatus 255
