### ISSUE TITLE
Lock being initialized twice

### ISSUE THREAD

**Issue by dividuum** [RPi-Distro/ffmpeg#9]
I got a `pthread_mutex_unlock failed with error: Operation not permitted` error when trying to play accelerated H264 videos on a Pi4 using a custom built version based on the Raspberry Pi OS bookworm `libavcodec` package's source code.

I think I tracked down the issue in this [forum post](https://forums.raspberrypi.com/viewtopic.php?t=363989). As all changes are tracked only in [form of a diff](https://github.com/RPi-Distro/ffmpeg/blob/pios/bookworm/debian/patches/ffmpeg-5.1.3-rpi_22.patch), I'm not sure how to suggest a fix.

**Comment by popcornmix** [comment]
FYI: @jc-kynesim is on holiday this week, so you may need to be patient waiting for a response.
(your analysis looks plausible to me though).

**Comment by jc-kynesim** [comment]
I'll look into that on Monday

**Comment by jc-kynesim** [comment]
No... I don't think your analysis is correct. context_init is indeed called twice but in between, as you note, there is a context_release (which is why the init is called again). Release destroys the ctx->lock so its completely legit to reinit it. Now if I've got something holding that lock whilst I release it or try to use it after I've released it then that would be bad.
Given that I don't have your issue this is hard for me to track down.

**Comment by dividuum** [comment]
Odd. I think it boils down to (assuming I'm on the correct branch `rpi_import_1`) `ff_mutex_lock`:

https://github.com/jc-kynesim/rpi-ffmpeg/blob/9011d22fed1834cb7bd946349cc8a5eda748eec7/libavcodec/v4l2_context.c#L930

when called from here

https://github.com/jc-kynesim/rpi-ffmpeg/blob/9011d22fed1834cb7bd946349cc8a5eda748eec7/libavcodec/v4l2_context.c#L402

The `ff_v4l2_context_release` in the reinit branch is called, but then bails out due to ctx->bufrefs being NULL. So the lock is still good. This was my initially wrong analysis as I thought the context was destroyed. But it's not in my case. Instead `ff_v4l2_context_set_status` is called, and locks the lock in line 930. It then calls `stuff_all_buffers` in line 933. There in line 902, `ff_v4l2_context_init` is called

https://github.com/jc-kynesim/rpi-ffmpeg/blob/9011d22fed1834cb7bd946349cc8a5eda748eec7/libavcodec/v4l2_context.c#L902

where the locked lock is initialized again:

https://github.com/jc-kynesim/rpi-ffmpeg/blob/9011d22fed1834cb7bd946349cc8a5eda748eec7/libavcodec/v4l2_context.c#L1280

The following unlock then fails. Here's the calling sequence when adding printfs to ff_mutex_init, ff_mutex_destory, ff_mutex_lock and ff_mutex_unlock:

```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36d08 init lock 0xede36e3c
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36d08 lock 0xede36e3c
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36d08 unlock 0xede36e3c
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36b88 lock 0xede36cbc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36b88 init lock 0xede36cbc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ctx 0xede36b88 unlock 0xede36cbc
pthread_mutex_unlock failed with error: Operation not permitted
Aborted
 ```

I hope I'm not doing anything else wrong, while using avcodec, but that's the sequence of events I see in my tests.

**Comment by jc-kynesim** [comment]
I'm still not sure your analysis is completely correct, but looking harder you are definitely right that I'm confused about where/when that lock should be inited/released. I've definitely run this under valgrind so I wonder why it didn't spot it... Anyway I'll fix this - thanks.

**Comment by dividuum** [comment]
I see that the code around `ff_v4l2_context_set_status` has now change a bit. I guess this issue can be closed now?

**Comment by jc-kynesim** [comment]
I believe this is now fixed - so yes. (I don't have that power)

**Comment by dividuum** [comment]
Thanks!
